frontend/src/components/BeatColumn/BeatBox.js
frontend/src/components/BeatColumn/BeatColumn.js

* 다른 사람이 누른 노트에 대한 악기, 노트 정보를 시각화 및 재생시 재생 가능
* 본인이 누른 노트는 현재 웹 소켓 통신 res를 받아와 취소됨
* 웹 소켓 통신 방식 변경 시 해결 가능

feat/협업 재생 기능 구현

---

backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/application/impl/SnapshotInstrumentMapImpl.java

스냅샷 생성 시 악기 다 피아노로 생성하도록 구현된 버그 수정했습니다.

hotfix : snapshotCreate

---

frontend/src/App.js
frontend/src/components/BeatColumn/BeatBox.js
frontend/src/components/BeatColumn/DrumBox.js
frontend/src/components/BeatGrid/BeatGrid.js
frontend/src/containers/WebSocket/WebSocketContainer.jsx
frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/pages/MyPage.jsx
frontend/src/pages/SnapshotPage.js
frontend/src/pages/WorkPlacePage.js

- 노트 소켓 통신 때 전달하는 spaceId 전달을 localStorage에서 꺼내는 것이 아닌, 페이지 파라미터에서 추출하여 수행하도록 수정

chore: 작업실 노트 소켓 통신 spaceId 전달 로직 수정

---

frontend/src/components/BeatColumn/BeatBox.js
frontend/src/components/BeatColumn/BeatColumn.js
frontend/src/components/BeatColumn/DrumBox.js
frontend/src/components/BeatGrid/BeatGrid.js
frontend/src/components/WorkSpace/Piano.js
frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/pages/WorkPlacePage.js

Feat/135 box UI수정 피아노,음계 표현

---

frontend/src/pages/LandingPage.jsx
frontend/src/pages/MyPage.jsx

- Navigation 에서 발생하는 로그인과 관련된 버그 수정

feat: 로그인 관련 버그 수정

---

frontend/src/components/BeatColumn/DrumBox.js

fix: 드럼 삭제 안되는 버그 해결

---

backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/api/WorkspaceController.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/application/WorkspaceService.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/application/impl/WorkspaceImpl.java

작업실 삭제 로직 notion에 명세서 적어 놨습니다.

feat : 작업실 삭제

---

backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/EditorSocketController.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/security/AccountPrinciple.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/security/WebSocketSecurityInterceptor.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/utility/WebSocketUtility.java
frontend/src/containers/WebSocket/WebSocketContainer.jsx

- add utility file for change header for simpMessagingTemplate format
- add principle for indexing websocket's sessionId
- change and add function to controller
- change and fix react socket destination, subscribe format

feat: 소켓 아키텍처 보강 및 기능 추가

---

backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/api/FileController.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/application/FileService.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/application/impl/FileServiceImpl.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/dao/AccountFileRepository.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/dto/FileRequest.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/entity/AccountFile.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/file/util/FileUtil.java
frontend/src/components/WorkSpace/ChangeAccountInfoModal.jsx
frontend/src/components/common/Header.js
frontend/src/pages/MyPage.jsx

- 회원의 사진 정보를 저장하는 API 구현
- Spring Resource 폴더에 파일을 저장하는 로직 구현
- 헤더 관련한 버그 수정
- 프론트 엔드 관련 버튼, 모달 스켈레톤 추가

feat: 회원 정보 수정 기능 일부 구현

---

frontend/src/components/BeatControls/BeatControls.js
frontend/src/containers/Note/NoteSearchModal.js
frontend/src/containers/workplace/CseContainer.jsx
frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/containers/workplace/WorkSpaceHeader.jsx
frontend/src/pages/WorkPlacePage.js

feat: 악보 찾기 UI 수정

---

frontend/src/pages/WorkPlacePage.js

fix: fix bug that image dose not seen

---

frontend/src/containers/WebSocket/WebSocketContainer.jsx
frontend/src/pages/WorkPlacePage.js

- acccountId 상태 값이 정상적으로 들어오지 않고 있었던 상황으로 문제 해결함

fix: 커서 버그 수정

---

frontend/src/api/fileStoreApi.jsx
frontend/src/components/Note/FileStoreModal.jsx
frontend/src/containers/WebSocket/WebSocketContainer.jsx
frontend/src/pages/WorkPlacePage.js

- 악보 저장 시 spaceId 값이 특정 상황에서 정상적으로 넘어오지 않는 현상으로 입장에 논리적으로 문제가 있는 흐름으로 접근할 때 발생하는 현상임
- 버그 수정함

fix: 모달과 관련된 버그 수정

---

frontend/src/App.js
frontend/src/VOC.jsx

- 프론트 VOC UI 작성
- VOC 관련 구글 폼 작성

feat: VOC 기능 추가

---

frontend/src/app/slices/innerContentSlice.js
frontend/src/components/BeatGrid/BeatGrid.js
frontend/src/components/WorkSpace/Piano.js
frontend/src/containers/WebSocket/WebSocketContainer.jsx

- **BeatGrid**: clicked row 상태 업데이트하여 <VerticalPiano> 컴포넌트에 prop으로 내려줌
- **VerticalPiano**: clicked row에 해당하는 index 찾은 뒤, 해당 css의 배경색 임시 변경

feat: 피아노 누른 지점 하이라이트 이펙트 구현

---

frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/pages/SnapshotPage.js
frontend/src/pages/WorkPlacePage.js

- column 수가 100 미만인 경우 100 으로 설정
- column 수가 100 이상인 경우, 최대값을 포함하도록 초기값 설정 (2마디 간격으로 끊어지도록 표시)
- column 수와 상관없이, 저장되어 있는 maxX 값 기준으로 타이트하게 초기값 설정
그 결과 짧은 스냅샷의 경우 이렇게 보이는데, 이 부분은 피드백 해주시면 수정할게요! 일단은 구현한 부분 merge 하겠습니다.

feat: 작업실, 스냅샷 maxX 초기 렌더링 반영

---

frontend/src/components/BeatControls/BeatChange.js
frontend/src/components/BeatGrid/BeatGrid.js
frontend/src/pages/SnapshotPage.js

- 스냅샷 maxX의 최솟값을 32로 설정
- 스냅샷에서는 column 바꾸는 버튼 표시되지 않도록 설정

feat: 스냅샷 수정

---

frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/pages/SnapshotPage.js
frontend/src/pages/WorkPlacePage.js

- 초기 렌더링되는 column 갯수가 무조건 8박자에 맞도록 수정

chore: 초기 렌더링 8박자에 맞춰지도록 수정

---

frontend/src/components/BeatGrid/BeatGrid.js

오해의 여지가 있어보이는 필요없는 props를 전달하는 코드 삭제했습니다.

fix : 필요없는 코드 삭제 + 재 렌더링 되는지 확인하는 콘솔 주석 해제

---

backend/letsnote/src/main/java/com/geeks/letsnote/global/infrastructure/api/AIModelController.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/infrastructure/application/AIModelService.java
frontend/src/api/workSpaceApi.js
frontend/src/components/WorkSpace/AIChordModal.js
frontend/src/components/WorkSpace/AIGenreModal.jsx
frontend/src/components/WorkSpace/AIInterfaceModal.jsx
frontend/src/pages/WorkPlacePage.js

- ### 기능 추가를 위한 변경점 추가됨
- 모델서버 엔드포인트 변경으로 인한 코드 수정
- 프론트엔드 인터페이스 수정 및 추가

feat: AI 노트 추천 서비스를 구현

---

frontend/src/api/workSpaceApi.js
frontend/src/components/WorkSpace/AIChordModal.js
frontend/src/pages/WorkPlacePage.js

- 화음 추천 기능 프론트 인터페이스 수정
- 화음 추천 기능 관련 API 수정

feat: AI 화음 추천 기능 추가

---

frontend/src/pages/WorkPlacePage.js

fix: change note piano to guitar

---

frontend/src/components/WorkSpace/AIChordModal.js
frontend/src/components/WorkSpace/AIGenreModal.jsx
frontend/src/pages/LandingPage.jsx
frontend/src/pages/WorkPlacePage.js

- 로직상 소켓통신이 일어났을 때, DB에 데이터를 저장해주고 있기 때문에 발생한 문제로 redux 상태값에 넣어준다고 해도 db 저장하는 로직을 타고 있지 않기 때문에 문제 발생
- 하위 컴포넌트에 부모 함수와 함께 해당 소켓 함수를 넘겨주고, 부모에 다시 전달하는 방식으로 문제 해결함

fix: AI 노트 추천 서비스 버그 수정

---

backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/EditorSocketController.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/WebRTCController.java
frontend/src/components/WorkSpace/SaveSnapshotModal.jsx
frontend/src/containers/WebSocket/WebSocketContainer.jsx
frontend/src/containers/workplace/WorkSpaceHeader.jsx
frontend/src/pages/WorkPlacePage.js

chore : webRTC 컨테이너에 spaceId props 전달 버그 수정 -> webRTC 음성 기능 정상 작동하도록 수정
스냅샷 -> 작품 수정,
멤버 추가 모달 사용자 반응 추가

chore : webRTC 컨테이너에 spaceId props 전달 버그 수정

---

frontend/src/components/Note/FileStoreModal.jsx
frontend/src/components/Note/SearchImageModal.jsx
frontend/src/components/WorkSpace/SaveCompleteModal.jsx
frontend/src/components/infra/GoogleCustomSearch.jsx
frontend/src/pages/WorkPlacePage.js

- 멘트가 영어로 되어있거나, 여전히 스냅샷이라고 되어있는 부분 수정

chore: 작업실 내 모달 멘트 수정

---

backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/EditorSocketController.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/WebRTCController.java

소켓 통신 시 유저가 중복으로 접속시 hashMap에 null 로 생성되는 버그때문에 동일한 유저가 두번들어오면 이후에 유저는 마우스 및 WebRTC 소켓 무시하도록 변경하고 null체크하도록 수정

fix : 소켓 통신 버그 수정

---

frontend/src/containers/workplace/WorkSpaceHeader.jsx

fix : 주영이형 CSS 덮은거 복구

---

frontend/src/containers/workplace/WorkSpaceHeader.jsx
frontend/src/pages/WorkPlacePage.js

chore : 헤더 재 렌더링 시 로컬스토리지에서 꺼내 쓰던 작업실 title이 사라져 렌더링되지 않던 버그 수정
feat : turn 서버 배치하여 다른 NAT 네트워크에서 접속 가능

turn 서버 배치 및 작업실 제목 수정

---

frontend/src/containers/Main/FeedContainer.jsx
frontend/src/containers/workplace/WorkSpaceContainer.js

- 피드 중앙 정렬 되도록 수정
- BPM 초기값 220으로 수정

feat: 피드 중앙정렬 되도록 수정

---

frontend/src/components/BeatColumn/BeatBox.js
frontend/src/components/BeatControls/BeatButton.js
frontend/src/components/BeatControls/BeatProgressBar.js
frontend/src/components/BeatControls/BeatToggle.js
frontend/src/components/BeatControls/BeatVolume.js
frontend/src/components/BeatControls/BeatsPerMinute.js
frontend/src/containers/workplace/WorkSpaceContainer.js
frontend/src/containers/workplace/WorkSpaceHeader.jsx

- 작업실 재생 중일 때 버튼 회색으로 바뀌도록 수정
- 화면 크기에 따라 진행바 길이 반응형으로 수정

feat: 작업실 재생버튼, 진행바 수정

---

frontend/src/components/BeatColumn/BeatBox.js
frontend/src/components/BeatColumn/DrumBox.js

chore : beatbox를 margin으로 구분선을 그은것 처럼 보이게 하던 방식을 실제로 구분선을 아래만 주는 방식으로 변경

chore : beatbox를 margin으로 구분선을 그은것 처럼 보이게 하던 방식을 실제로 구분선을 아래만 주는 방식으로 변경

---

backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/api/FeedController.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/application/impl/SnapshotImpl.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/dto/ResponseNotes.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/EditorSocketController.java
backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/WebRTCController.java
frontend/src/containers/workplace/WorkSpaceHeader.jsx

rtc 버그들 다 잡고 snapshot api에 타이틀 제공하도록 변경했습니다.

Back/chore/fix logic+fix snapshot api

---

backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/application/impl/SnapshotImpl.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/dto/RequestSnapshot.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/snapshot/entity/Snapshot.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/application/impl/WorkspaceImpl.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/dto/ResponseNotes.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/dto/ResponseWorkspaces.java
backend/letsnote/src/main/java/com/geeks/letsnote/domain/studio/workSpace/entity/Workspace.java
frontend/src/components/Audio/index.jsx

- 작업실 / 스냅샷 bpm 저장하도록 수정
- 상대방 볼륨 0.2 -> 0.5로 수정

Back/feat/bpm 저장

---

frontend/src/app/slices/cursorSlice.js
frontend/src/components/WorkSpace/Cursor/Cursors.jsx
frontend/src/containers/workplace/WorkSpaceHeader.jsx

- 작업실 퇴장시 모든 커서 정보 청소하고 나가도록 수정

feat: 커서 삭제 구현 마무리

---

backend/letsnote/src/main/java/com/geeks/letsnote/global/network/api/EditorSocketController.java
frontend/src/components/BeatGrid/BeatGrid.js
frontend/src/containers/WebSocket/WebSocketContainer.jsx

chore : 마우스 클릭 비동기화 하여 0.179 -> 0.041 초로 통신 전송 시간 단축

chore : 마우스 클릭 비동기화 하여 0.179 -> 0.041 초로 통신 전송 시간 단축

---

frontend/src/api/authApi.js
frontend/src/api/axiosInstance.js
frontend/src/components/auth/AuthModule.jsx

- axios instance에 response Intercepter 추가
- 액세스 토큰 재발급 로직 구현

feat: JWT 프론트 코드 일부 수

---

frontend/src/components/Audio/index.jsx
frontend/src/containers/workplace/WorkSpaceHeader.jsx

작업실에서 나갈때, 내 로컬 스트림 off를 안해서 여러 탭으로 여러번 시도하면 부하가 발생하는 문제가 있었어요.
-> unmount될때, 로컬스트림 off하도록 수정했습니다.
그리고 상대방의 마이크 볼륨 0.5 -> 1로 두배 올렸습니다.

Front/chore/mylocal off when unmonut+볼륨 1로 증가
